#Minecraft server properties
online-mode=false
enforce-secure-profile=false
spawn-protection=0
max-players=100
difficulty=normal
gamemode=survival
hardcore=false
pvp=true
allow-flight=false
view-distance=10
simulation-distance=8
motd=Private server
enable-command-block=false
white-list=false
enforce-whitelist=false
level-name=world
level-seed=1220498775
level-type=minecraft\:normal
generate-structures=true
max-build-height=320
allow-nether=true
enable-nether=true
op-permission-level=4
function-permission-level=2
max-tick-time=60000
network-compression-threshold=256
rate-limit=0
player-idle-timeout=0
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
resource-pack-sha1=
resource-pack-id=
require-resource-pack=false
enable-rcon=false
rcon.password=
rcon.port=25575
enable-query=false
query.port=25565
server-ip=
server-port=25565
